
name: dagster_clickhouse
services:
  clickhouse-server:
    container_name: uoles-clickhouse-dagster-25
    image: uoles/clickhouse:25.2.1
    environment:
      CLICKHOUSE_DB: my_database 
      CLICKHOUSE_USER: username 
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1 
      CLICKHOUSE_PASSWORD: password 
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - code_location
    links: 
      - code_location

  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  webserver:
    build:
      context: .
      dockerfile: .docker/webserver.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  code_location:
    build:
      context: .
      dockerfile: .docker/code-location.Dockerfile
    env_file:
      - .env
    ports:
      - "5678:5678"
    entrypoint: python
    command:
      - -m
      - debugpy
      - --listen
      - 0.0.0.0:5678
      - -m
      - dagster
      - code-server
      - start
      - -h
      - 0.0.0.0
      - -p
      - "4000"
      - -m
      - defs

  daemon:
    build:
      context: .
      dockerfile: .docker/daemon.Dockerfile
    env_file:
      - .env
