version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: userpg
      POSTGRES_PASSWORD: passwordpg
    ports:
      - 5432:5432
    depends_on: 
      - clickhouse-server
    links: 
      - clickhouse-server

  clickhouse-server:
    container_name: uoles-clickhouse-pg-25
    image: uoles/clickhouse:25.2.1
    environment:
      CLICKHOUSE_DB: my_database 
      CLICKHOUSE_USER: username 
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1 
      CLICKHOUSE_PASSWORD: password 
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144      
