version: "3.6"

services:
  clickhouse-server:
    container_name: clickhouse
    image: uoles/clickhouse:25.2.1
    hostname: clickhouse-server
    build:
      context: .
      dockerfile: clickhouse-25.2.1.Dockerfile
    environment:
      CLICKHOUSE_DB: my_database
      CLICKHOUSE_USER: username
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: password
    ports:
      - "18123:8123"
      - "19000:9000"
      - "19363:9363"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - default

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9002'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
