version: "3.6"

services:
  clickhouse-server:
    container_name: clickhouse
    image: uoles/clickhouse:25.2.1
    hostname: clickhouse-server
    build:
      context: .
      dockerfile: clickhouse-25.2.1.Dockerfile
    environment:
      CLICKHOUSE_DB: my_database
      CLICKHOUSE_USER: username
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: password
    ports:
      - "18123:8123"
      - "19000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - default
    depends_on:
      - minio
      - createbuckets

  minio:
    image: quay.io/minio/minio
    container_name: minio
    hostname: minio
    command: server --address 0.0.0.0:10000 --console-address 0.0.0.0:10001 /data
    ports:
      - "10000:10000"
      - "10001:10001"
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - default

  createbuckets:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:10000 minio-root-user minio-root-password;
      /usr/bin/mc admin info myminio;
      /usr/bin/mc mb myminio/clickhouse;
      /usr/bin/mc policy set public myminio/clickhouse;
      exit 0;
      "
    depends_on:
      - minio
    links:
      - minio
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
