general:
  remote_storage: s3
  disable_progress_bar: false
  backups_to_keep_local: 0
  backups_to_keep_remote: 0
  log_level: info
  allow_empty_backups: false
clickhouse:
  username: username
  password: password
  skip_tables:
  - system.*
  - INFORMATION_SCHEMA.*
s3:
  access_key: minio-root-user
  secret_key: minio-root-password
  bucket: ""
  endpoint: http://minio:10000/clickhouse/
  region: us-west-000
  acl: ""
  force_path_style: false
  path: clickhouse-backup
  disable_ssl: false
  part_size: 536870912
  compression_level: 1
  compression_format: tar
  sse: ""
  disable_cert_verification: false
  storage_class: STANDARD