global:
  scrape_interval: 10s
scrape_configs:
  - job_name: clickhouse_metrics
    static_configs:
      - targets:
        - clickhouse-server:9363
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: "/metrics"
